### ISSUE TITLE
Add a remote certificate

### ISSUE THREAD

**Issue by GCalmels** [tschoffelen/php-pkpass#82]
I have a certificate in S3 and I have an error in the PKPass constructor. I guess it is normal because `file_exists` does not work with remote files but is there a solution to add a remote certificate ?

**Comment by tschoffelen** [comment]
True, I guess file_exists doesn't work, so the library would require code changes, unless of course you would be okay with temporarily storing the certificate locally and then removing it after use, which I guess `file_get_contents` internally would also do when using a remote file URL.

I would be okay with accepting a PR to change the library so that it accepts remote URLs for the certificate.

**Comment by tschoffelen** [comment]
Fixed in #83.
