### ISSUE TITLE
Not visible on watch

### ISSUE THREAD

**Issue by sweebee** [tschoffelen/php-pkpass#88]
### Expected Behavior
When added to iphone, it should appear on the apple watch. I've got passes from other companies which are added to the apple watch wallet. But my passes which i create with this package wont show on the watch.

### Actual Behavior
Not visible on the watch

### Steps to Reproduce the Problem

  1. create pass
  2. add to iphone wallet
  3. its not visible on watch

**Comment by tschoffelen** [comment]
I'm guessing this is not related to the library, since it only does the packaging, but rather some kind of limitation on pass features that are supported on the Apple Watch.

Some things that come to mind that could cause a problem:

- Certain types of passes might not show up on the Watch? E.g. loyalty cards?
- Certain types of barcodes might not be supported

**Comment by tschoffelen** [comment]
Any updates @sweebee?

**Comment by sweebee** [comment]
I’ve got it working. Looks like some field types are not supported on the watch.
